import { useTranslate } from '@tolgee/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import LanguageSelect from '../src/components/LanguageSelect';

import styles from '../styles/Home.module.css';

const Contact: NextPage = () => {
  const t = useTranslate();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{t('contact.title')}</h1>
      </main>

      <div>
        <LanguageSelect />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Contact
